### ISSUE TITLE
Ajout order by sur request hgt

### ISSUE THREAD

**Issue by logscl** [jlamby/nicobot-persistence#12]
Issue Github pour pas l'oublier:

Moyen d'ajouter un `ORDER BY count(user_id) DESC` ici (et à la ligne en dessous) ? https://github.com/jlamby/nicobot-persistence/blob/51d203732c2fc2bc7c8c164685b0a2ab9cdcfa92/src/hgt/HgtDao.ts#L10

Merci !

**Comment by jlamby** [comment]
Fixed in #13
