### ISSUE TITLE
Add service for HGT score

### ISSUE THREAD

**Issue by jlamby** [jlamby/nicobot-persistence#3]
Add/update score 
Get score

**Comment by logscl** [comment]
Structure DB
- UserID (varchar 20)
- ChannelID (varchar 20)
--- Soit:
- Date
--- Soit:
- Week (int)
- Year (int)

pour le moment je suis dans le modèle week + year (a cause de jooq), mais ca peut marcher avec une date aussi.

**Comment by logscl** [comment]
endpoints:

-    void addGreeters(String channel, Set<String> users);

-    Map<String, Integer> getWeeklyGreeters(String channel); <userid, count>

-    Map<String, Integer> getAllTimeGreeters(String channel); <userid, count>, year = current_year, peut passer en param si nécessaire

**Comment by jlamby** [comment]
Fait et deployé
